apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trm-workspace-rwx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: shared-vast
