apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspect
spec:
  restartPolicy: Never
  containers:
    - name: sh
      image: alpine:3.19
      command: ["/bin/sh","-lc","sleep 3600"]
      volumeMounts:
        - name: trm-workspace
          mountPath: /workspace
  volumes:
    - name: trm-workspace
      persistentVolumeClaim:
        claimName: trm-workspace-pvc
