apiVersion: batch/v1
kind: Job
metadata:
  name: trm-dataset-builder
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: builder
          image: python:3.10-slim
          imagePullPolicy: IfNotPresent
          command: ["bash","/script/run.sh"]
          volumeMounts:
            - name: trm-workspace
              mountPath: /workspace
            - name: script
              mountPath: /script
            - name: kaggle-token
              mountPath: /root/.kaggle
              readOnly: true
          resources:
            requests:
              cpu: "4"
              memory: 16Gi
            limits:
              cpu: "8"
              memory: 32Gi
      volumes:
        - name: trm-workspace
          persistentVolumeClaim:
            claimName: trm-workspace-pvc
        - name: script
          configMap:
            name: trm-dataset-script
            defaultMode: 0755
        - name: kaggle-token
          secret:
            secretName: kaggle-api-token
            defaultMode: 0600
